services:
  app:
    image: antonchik/diplom
    ports:
    - 3000:3000
    networks:
    - app-network
    depends_on:
    - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      MONGO_URL: mongodb://localhost:27017/
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge